name: BuildFFA
version: 4.0
main: org.vansama.buildffa.BuildFFA
author: muvixo
description: BuildFFA - Created by Muvixo
commands:
  buildffa:
    description: Main BuildFFA command
    usage: /buildffa <help|kiteditor|setvoid|sethighlimit|setspawn|buildmode|ypvp|sb|stats|top|resetstats|cc|creator|reload>
    aliases:
      - bffa
permissions:
  buildffa.kiteditor:
    description: Allows using the Kit Editor
    default: true
  buildffa.setvoid:
    description: Allows setting the void kill height
    default: true
  buildffa.sethighlimit:
    description: Allows setting the high build limit
    default: true
  buildffa.setspawn:
    description: Allows setting the respawn point
    default: true
  buildffa.reload:
    description: Allows reloading the config
    default: true
  buildffa.highlimit.bypass:
    description: Bypass the high-limit build restriction
    default: op
  buildffa.ypvp:
    description: Allows setting the YPvP Y level
    default: op
  buildffa.ypvp.bypass:
    description: Bypass the YPvP PvP restriction
    default: op
  buildffa.buildmode:
    description: Allows toggling build mode decorative command
    default: true
  buildffa.scoreboard.toggle:
    description: Allows toggling the scoreboard visibility
    default: true
  buildffa.resetstats:
    description: Allows resetting player stats
    default: op
  buildffa.connection:
    description: Allows managing connection check
    default: op
  buildffa.connection.bypass:
    description: Bypass the connection check kick (grant manually or use /buildffa cc bypass)
    default: false