name: BuildFFA
version: 4.0
main: org.vansama.buildffa.BuildFFA
author: VanSaMa
description: BuildFFA plugin with GUI Kit Editor - Created by Muvixo
commands:
  buildffa:
    description: Main BuildFFA command
    usage: /buildffa <help|kiteditor|setvoid|sethighlimit|setspawn|creator|reload>
    aliases:
      - bffa
permissions:
  buildffa.kiteditor:
    description: Allows using the Kit Editor
    default: true
  buildffa.setvoid:
    description: Allows setting the void kill height
    default: true
  buildffa.sethighlimit:
    description: Allows setting the high build limit
    default: true
  buildffa.setspawn:
    description: Allows setting the respawn point
    default: true
  buildffa.reload:
    description: Allows reloading the config
    default: true
  buildffa.highlimit.bypass:
    description: Bypass the high-limit build restriction
    default: true